services:
  sam2-gradio:
    #build:
    #   context: .
    image: "ghcr.io/michael-mueller-git/sam2-gradio:latest"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "7860:7860"
    ipc: host
